name: Toad Life
favicon: null
layout_spectrum: 0.6437075089197606
typography_spectrum: 0.5101809098850936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6549894365016371
  lightness: 0.6561186830513179
  saturation: 0.32945961016230285
  rhythmicContrast: 0.2687413936946541
purpose: []
